### ISSUE TITLE
Weapon Traits Excess Information Issue

### ISSUE THREAD

**Issue by shadowfray** [Bathtor/EPSheet#77] opened 2022-01-15 04:16 UTC
The weapons area of the character sheet seems to display a lot [more information](https://gyazo.com/f83443429e7e8fcbf2e512248f2e0be5) than I suspect is supposed to be there. We really appreciated the fix with the skills and traits :)

**Comment by Bathtor** [comment] 2022-01-15 10:06
Hmm, no. That looks as intended to me.
There is a lot of information about weapons one usually needs at a glance, so I tried to find a very compressed format that gives you all of that information.

I'll close this as "not an issue" for now, but if you have suggestions for a better presentation of the same information, feel free to send a PR or a mockup.

**Closed as completed by Bathtor** 2022-01-15 10:06 UTC
Labels: invalid
